const tools=[
 {n:'Make',c:'Automazione',p:'Freemium',d:'Scenari visuali per collegare app, dati e operazioni.',b:'Flussi articolati senza programmare',w:['Notion','Google Sheets','Webhook'],u:'https://www.make.com/',x:'#7659f5'},
 {n:'Zapier',c:'Automazione',p:'Freemium',d:'Automazioni rapide con migliaia di integrazioni pronte.',b:'Iniziare velocemente',w:['Gmail','Trello','HubSpot'],u:'https://zapier.com/',x:'#ff4f00'},
 {n:'n8n',c:'Automazione',p:'Open source',d:'Flussi avanzati, anche installati sul proprio server.',b:'Controllo dei dati',w:['Supabase','API','AI'],u:'https://n8n.io/',x:'#e94b70'},
 {n:'ChatGPT',c:'Intelligenza artificiale',p:'Freemium',d:'Assistente per scrittura, analisi, ricerca e programmazione.',b:'Lavoro quotidiano',w:['Notion','Canva','GitHub'],u:'https://chatgpt.com/',x:'#10a37f'},
 {n:'Claude',c:'Intelligenza artificiale',p:'Freemium',d:'AI utile per testi lunghi, documenti e codice.',b:'Documenti estesi',w:['Drive','GitHub','API'],u:'https://claude.ai/',x:'#c15f3c'},
 {n:'Supabase',c:'Database',p:'Freemium',d:'Database, autenticazione e archiviazione per applicazioni moderne.',b:'Dati persistenti',w:['Next.js','n8n','Netlify'],u:'https://supabase.com/',x:'#3ecf8e'},
 {n:'Airtable',c:'Database',p:'Freemium',d:'La semplicità di un foglio con funzioni da database.',b:'Archivi e piccoli team',w:['Make','Zapier','Forms'],u:'https://airtable.com/',x:'#18bfff'},
 {n:'Baserow',c:'Database',p:'Open source',d:'Alternativa no-code ad Airtable disponibile in cloud o self-hosted.',b:'Più controllo sull’infrastruttura',w:['n8n','API','Form'],u:'https://baserow.io/',x:'#5190ef'},
 {n:'SmartSuite',c:'Database',p:'Freemium',d:'Workspace no-code orientato a processi, progetti e operazioni aziendali.',b:'Flussi strutturati per team',w:['Fillout','Make','Zapier'],u:'https://www.smartsuite.com/',x:'#6c5ce7'},
 {n:'GitHub',c:'Siti e app',p:'Gratis',d:'Conserva il codice e tiene traccia di ogni modifica.',b:'Versioni e backup',w:['Netlify','Cloudflare','VS Code'],u:'https://github.com/',x:'#24292f'},
 {n:'Netlify',c:'Siti e app',p:'Freemium',d:'Pubblica un sito e lo aggiorna automaticamente dal repository.',b:'Siti statici',w:['GitHub','Supabase','Forms'],u:'https://www.netlify.com/',x:'#00a99d'},
 {n:'Microsoft Clarity',c:'Marketing',p:'Gratis',d:'Registrazioni e mappe di calore per capire come viene usato un sito.',b:'Analisi del comportamento',w:['Analytics','GTM','Siti web'],u:'https://clarity.microsoft.com/',x:'#1678f2'},
 {n:'Notion',c:'Organizzazione',p:'Freemium',d:'Note, procedure, progetti e piccoli database.',b:'Conoscenza condivisa',w:['Make','Drive','AI'],u:'https://www.notion.so/',x:'#191919'},
 {n:'Obsidian',c:'Organizzazione',p:'Gratis',d:'Note locali collegate e conservate sul computer.',b:'Archivio personale duraturo',w:['Markdown','GitHub','Plugin'],u:'https://obsidian.md/',x:'#7c3aed'}
 ,{n:'Tally',c:'Form e raccolta dati',p:'Freemium',d:'Moduli con stile essenziale; piano gratuito con moduli e invii illimitati entro le regole di uso corretto.',b:'Raccogliere dati con pochi costi',w:['Notion','Make','Google Sheets'],u:'https://tally.so/',x:'#333333'}
 ,{n:'Typeform',c:'Form e raccolta dati',p:'Freemium',d:'Moduli conversazionali e curati, con piani a pagamento e limiti di risposte.',b:'Esperienze di compilazione visive',w:['Zapier','CRM','Webhooks'],u:'https://www.typeform.com/',x:'#262627'}
 ,{n:'Fillout',c:'Form e raccolta dati',p:'Freemium',d:'Moduli avanzati che possono creare e aggiornare record in Airtable e altri database.',b:'Form collegati direttamente ai dati',w:['Airtable','Notion','SmartSuite'],u:'https://www.fillout.com/',x:'#7b61ff'}
 ,{n:'Anytype',c:'Organizzazione',p:'Freemium',d:'Workspace local-first, cifrato end-to-end e basato su oggetti.',b:'Privacy e uso anche offline',w:['Oggetti','Relazioni','Sync'],u:'https://anytype.io/',x:'#ff5c35'}
 ,{n:'Capacities',c:'Organizzazione',p:'Freemium',d:'Note organizzate come oggetti collegati invece che come semplici file e cartelle.',b:'Studio, ricerca e conoscenza collegata',w:['Oggetti','AI','Calendario'],u:'https://capacities.io/',x:'#2d6cdf'}
 ,{n:'Perplexity',c:'Intelligenza artificiale',p:'Freemium',d:'Motore di risposta orientato alla ricerca sul web e alle fonti consultabili.',b:'Ricerca e prima raccolta di fonti',w:['Web','API','Report'],u:'https://www.perplexity.ai/',x:'#1f7a7a'}
 ,{n:'Gemini',c:'Intelligenza artificiale',p:'Freemium',d:'Assistente Google per ricerca, documenti, immagini e funzioni multimediali disponibili secondo il piano.',b:'Lavorare con l’ecosistema Google',w:['Workspace','NotebookLM','Veo'],u:'https://gemini.google.com/',x:'#4d7cff'}
 ,{n:'NotebookLM',c:'Ricerca e conoscenza',p:'Freemium',d:'Analizza e sintetizza fonti caricate dall’utente mantenendo i riferimenti ai documenti.',b:'Studiare PDF e raccolte documentali',w:['Drive','PDF','Gemini'],u:'https://notebooklm.google.com/',x:'#3569d4'}
 ,{n:'Cursor',c:'Sviluppo e codice',p:'Freemium',d:'Editor AI progettato per comprendere e modificare progetti di codice completi.',b:'Sviluppo assistito su repository',w:['GitHub','Supabase','Netlify'],u:'https://cursor.com/',x:'#1c1c1c'}
 ,{n:'Windsurf',c:'Sviluppo e codice',p:'Freemium',d:'Editor con agente AI e strumenti per intervenire su più file del progetto.',b:'Prototipi e refactoring assistito',w:['GitHub','API','Deploy'],u:'https://windsurf.com/',x:'#00a98f'}
 ,{n:'v0',c:'Sviluppo e codice',p:'Freemium',d:'Genera interfacce e prototipi web a partire da istruzioni testuali.',b:'Partire rapidamente dalla UI',w:['React','Vercel','GitHub'],u:'https://v0.dev/',x:'#111111'}
 ,{n:'Bolt.new',c:'Sviluppo e codice',p:'Freemium',d:'Ambiente nel browser per generare e modificare applicazioni tramite prompt.',b:'Creare prototipi funzionanti',w:['Supabase','GitHub','Netlify'],u:'https://bolt.new/',x:'#6b46ff'}
 ,{n:'GitHub Copilot',c:'Sviluppo e codice',p:'A pagamento',d:'Assistente integrato negli editor e nei flussi GitHub per scrivere e rivedere codice.',b:'Sviluppo quotidiano',w:['VS Code','GitHub','Repository'],u:'https://github.com/features/copilot',x:'#24292f'}
 ,{n:'Firebase',c:'Database',p:'Freemium',d:'Servizi Google per database, autenticazione, hosting e funzioni backend.',b:'Backend gestito rapidamente',w:['Gemini','Web app','Android'],u:'https://firebase.google.com/',x:'#f5a623'}
 ,{n:'Activepieces',c:'Automazione',p:'Open source',d:'Piattaforma di automazione disponibile in cloud o installabile autonomamente.',b:'Alternativa moderna per i flussi',w:['AI','Webhook','Self-hosted'],u:'https://www.activepieces.com/',x:'#6c5ce7'}
 ,{n:'Dify',c:'Agenti AI',p:'Open source',d:'Piattaforma per costruire applicazioni AI, flussi e assistenti collegati ai propri documenti.',b:'Prototipi RAG e chatbot',w:['Modelli AI','API','Knowledge base'],u:'https://dify.ai/',x:'#155eef'}
 ,{n:'Flowise',c:'Agenti AI',p:'Open source',d:'Strumento visuale per creare flussi e applicazioni basate su modelli linguistici.',b:'Sperimentare agenti visualmente',w:['LangChain','API','Database vettoriali'],u:'https://flowiseai.com/',x:'#2c8b75'}
 ,{n:'Runway',c:'Grafica e video',p:'Freemium',d:'Generazione e trasformazione video da testo, immagini, video o audio.',b:'Scene animate e contenuti promozionali',w:['Immagini','Audio','Montaggio'],u:'https://runwayml.com/',x:'#181818'}
 ,{n:'Ideogram',c:'Grafica e video',p:'Freemium',d:'Generatore di immagini particolarmente adatto a grafiche che includono testo.',b:'Concept grafici e titoli visivi',w:['Canva','Photoroom','Social'],u:'https://ideogram.ai/',x:'#ef3c5b'}
 ,{n:'Photoroom',c:'Grafica e video',p:'Freemium',d:'Rimuove sfondi e prepara immagini di prodotto o contenuti per siti e social.',b:'Pulizia rapida degli asset',w:['Canva','E-commerce','Social'],u:'https://www.photoroom.com/',x:'#7357ff'}
 ,{n:'Canva',c:'Grafica e video',p:'Freemium',d:'Crea grafiche, presentazioni e video con modelli e strumenti assistiti dall’AI.',b:'Contenuti pronti per la pubblicazione',w:['ChatGPT','Runway','Social'],u:'https://www.canva.com/',x:'#00a8c6'}
];
const categories=['Tutti',...new Set(tools.map(t=>t.c))];let active='Tutti',expanded=false;
const searchHints={video:'video immagini grafica social reel montaggio animazione',immagini:'immagini grafica foto design',sito:'sito web pubblicazione hosting pagina',app:'app webapp applicazione prototipo codice',automatizzare:'automazione flusso webhook collegare',richieste:'form lead contatti crm preventivi',clienti:'lead crm form database',note:'organizzazione conoscenza documenti',studiare:'ricerca conoscenza documenti pdf note',database:'database dati archivio backend',misurare:'marketing analytics tracciamento conversioni'};
const searchStopWords=new Set(['creare','fare','vorrei','voglio','serve','servono','uno','una','un','il','lo','la','i','gli','le','di','da','per','con','che','mio','mia']);
const grid=document.querySelector('#tool-grid'),search=document.querySelector('#search'),filters=document.querySelector('#filters'),more=document.querySelector('#more');
function render(){const found=tools.filter(t=>active==='Tutti'||t.c===active);document.querySelector('#result-count').textContent=`${found.length} strumenti`;document.querySelector('#empty').style.display=found.length?'none':'block';more.style.display=found.length>6?'block':'none';more.textContent=expanded?'Mostra meno ↑':'Vedi tutti gli strumenti ↓';grid.innerHTML=(expanded?found:found.slice(0,6)).map(t=>`<article class="tool-card"><div class="card-top"><span class="tool-logo" style="background:${t.x}">${t.n[0]}</span><span class="badge">${t.p}</span></div><p class="tool-category">${t.c}</p><h3>${t.n}</h3><p>${t.d}</p><div class="ideal">✓ <span><b>Ideale per</b>${t.b}</span></div><label>FUNZIONA BENE CON</label><div class="tags">${t.w.map(w=>`<span>${w}</span>`).join('')}</div><a href="${t.u}" target="_blank" rel="noopener">Visita il sito ufficiale ↗</a></article>`).join('')}
function drawFilters(){filters.innerHTML=categories.map(c=>`<button class="${c===active?'active':''}" data-cat="${c}">${c}</button>`).join('');filters.querySelectorAll('button').forEach(b=>b.onclick=()=>{active=b.dataset.cat;expanded=false;drawFilters();render();if(window.matchMedia('(max-width: 820px)').matches)setTimeout(()=>grid.scrollIntoView({behavior:'smooth',block:'start'}),50)})}
more.onclick=()=>{expanded=!expanded;render()};const menu=document.querySelector('.menu-button');menu.onclick=()=>{const nav=document.querySelector('nav');nav.classList.toggle('open');menu.setAttribute('aria-expanded',nav.classList.contains('open'))};drawFilters();render();
